name: Deploy GH

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build VitePress docs
        run: npm run docs:build

      - name: Merge static root into VitePress dist
        run: |
          OUT=docs/.vitepress/dist
          # s’assure que le dossier existe (VitePress le crée, mais au cas où)
          mkdir -p "$OUT"
          # copie le site statique racine dans la sortie VitePress
          cp -r index.html assets "$OUT"/
          # évite l’interférence Jekyll sur Pages
          touch "$OUT"/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
